### ISSUE TITLE
Config not existing 

### ISSUE THREAD

**Issue by Tuvqlu** [BeeAZZ/Oneblock-PM4#11]
![A87FE3FE-E917-4189-828F-C4069E6004B1](https://user-images.githubusercontent.com/98550458/152569547-beea69a2-734a-4ecd-96c4-932cf7f31a56.jpeg)
Hey I’m really excited for this update, but when I open the file I see no config

**Comment by lenlenlL6** [comment]
I have updated the patch. Let's check it
https://github.com/lenlenlL6/Oneblock-PM4/releases/tag/FIX_CONFIG
