### ISSUE TITLE
More Ideas

### ISSUE THREAD

**Issue by Tuvqlu** [BeeAZZ/Oneblock-PM4#12]
For version 0.04 here are some ideas:

- Ability to let someone build on your island
- Ability to change the UI in config.yml
- Ability to create joint islands
- Ability to have a main island where shops can be and everyone can go

**Comment by lenlenlL6** [comment]
I would consider

**Comment by NhanAZ** [comment]
> Not related to this issue

@Tuvqlu How can I contact you?
