### ISSUE TITLE
Crash PM4

### ISSUE THREAD

**Issue by TaxosTV** [BeeAZZ/Oneblock-PM4#14]
Hello everybody! When using the plugin, the following error occurs.

2022-02-19 [14:41:25.573] [Server thread/CRITICAL]: pocketmine\utils\AssumptionFailedError: "Position world is null or has been unloaded" (EXCEPTION) in "pmsrc/src/world/Position" at line 70

  #0 pmsrc/src/entity/Entity(1397): pocketmine\world\Position->getWorld()
  #1 pmsrc/src/player/Player(2354): pocketmine\entity\Entity->teleport(object pocketmine\world\Position#125314, NULL , NULL )
  #2 plugins/Oneblock-PM4/src/lenlenlL6/oneblock/Oneblock(259): pocketmine\player\Player->teleport(object pocketmine\world\Position#125314)
  #3 plugins/Oneblock-PM4/src/lenlenlL6/oneblock/libs/jojoe77777/FormAPI/Form(46): lenlenlL6\oneblock\Oneblock->lenlenlL6\oneblock\{closure}(object ipad54\netherblocks\player\Player#126029, integer 0)

**Comment by Zelurium** [comment]
Hello, I have the same error

**Comment by lenlenlL6** [comment]
After you do what do you get this error?
