### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by PyYakro** [BeeAZZ/Oneblock-PM4#15]
- Add UI texts to lang.yml with color customization
- Add custom tiers
- Add placeholders for ScoreBoard (Scorehud plugin)
- Change format in config.yml (change num id to text id)
- Change the spawn of blocks so that when gravel and sand are shed, the blocks are replaced, and not disappeared
- Add chests for each tier with customizable items
- Add smooth movement between worlds (Sometimes when moving, visual bugs remain with chunks of the past world)

Thank you for a good plugin, if I could, I would customize plugin myself :)

**Comment by lenlenlL6** [comment]
I would consider
