### ISSUE TITLE
Big Problem

### ISSUE THREAD

**Issue by Tuvqlu** [BeeAZZ/Oneblock-PM4#16]
Hey Len, big error I’ve found that should be fixed ASAP. When editing config, if you type a block or id that won’t work with your plugin, for example frosted ice or lava, it spawns a random block. Unfortunately, this causes ender rods to be placed in the first tier, and as well, blocks like border blocks appear, which cannot be broken. As well, sometimes it just breaks, and no block spawns back, and you can’t break that block or put anything in to replace it. I suggest Making it so if a block doesn’t register, just make it stone or dirt. Thanks.

**Comment by lenlenlL6** [comment]
Please reset the config and read the comments carefully, you may have edited it wrong.

**Comment by Tuvqlu** [comment]
Yup, was looking at the wrong block list LOl
