### ISSUE TITLE
crashes when teleporting

### ISSUE THREAD

**Issue by Tuvqlu** [BeeAZZ/Oneblock-PM4#17]
pocketmine\world\WorldManager::loadWorld(): Argument #1 ($name) must be of type string, pocketmine\world\World given, called in phar:///home/container/plugins/Oneblock-PM4 (2).phar/src/lenlenlL6/oneblock/Oneblock.php on line 258

**Comment by BeeAZ-pm-pl** [comment]
I fixed it please rate me 5 star at poggit

**Comment by Tuvqlu** [comment]
Yep it’s fixed
