### ISSUE TITLE
🐛 » Bug

### ISSUE THREAD

**Issue by SlidexDE** [BeeAZZ/Oneblock-PM4#20]
Hello! If you create an island, stand on the eye and then dismantle it, it takes a short time for the block to reappear. In time, however, you fall out of the world. The problem should actually be solved by teleporting the person up a block at the Y coordinate. Thank you in advance!

**Comment by lenlenlL6** [comment]
I fixed it

**Comment by SlidexDE** [comment]
> I fixed it

Unfortunately, it still doesn't work :/

**Comment by SlidexDE** [comment]
Hello?

**Comment by SlidexDE** [comment]
@BeeAZ-pm-pl @DavidGlitch04 @lenlenlL6

**Comment by BeeAZ-pm-pl** [comment]
Place blocks next to
