### ISSUE TITLE
Invite to your island.

### ISSUE THREAD

**Issue by VisKaRaZe** [BeeAZZ/Oneblock-PM4#21]
Hello !
How about inviting someone to your island?
Thank you

**Comment by VisKaRaZe** [comment]
Apparently we can invite no one to the island... Which is problematic, it would be better if we could invite players to the islands because we can add friends but we can't invite them to the island... Thank you very much in advance

**Comment by BeeAZ-pm-pl** [comment]
@lenlenlL6
