### ISSUE TITLE
Gravel/Falling Blocks

### ISSUE THREAD

**Issue by LeoWasCoding** [BeeAZZ/Oneblock-PM4#22]
So i edited the configs and added some blocks for plains tier like gravels and sand stuffs, then when the gravel/sand spawns it falls (i know that) but it doesnt regenerate another block. If there is a way for you guys to add a bedrock beneath the generator it would be a life savior

**Comment by lenlenlL6** [comment]
@BeeAZ-pm-pl

**Comment by BeeAZ-pm-pl** [comment]
Ok

**Comment by LeoWasCoding** [comment]
We always meeting on may 20.. Im 4 days late.. Need ya help anyways. @BeeAZ-pm-pl
