### ISSUE TITLE
Crashed happened by doing /oneblock !!! Help needed asap.

### ISSUE THREAD

**Issue by LeoWasCoding** [BeeAZZ/Oneblock-PM4#25]
Fatal error: During inheritance of JsonSerializable: Uncaught ErrorException: Return type of jojoe77777\FormAPI\Form::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/container/plugins/FormAPI_dev-2.phar/src/jojoe77777/FormAPI/Form.php:53
Stack trace:
#0 phar:///home/container/plugins/FormAPI_dev-2.phar/src/jojoe77777/FormAPI/Form.php(10): pocketmine\errorhandler\ErrorToExceptionHandler::handle(8192, 'Return type of ...', 'phar:///home/co...', 53)
#1 phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php(93): include('phar:///home/co...')
#2 phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php(83): BaseClassLoader->loadClass('jojoe77777\\Form...')
#3 phar:///home/container/plugins/FormAPI_dev-2.phar/src/jojoe77777/FormAPI/SimpleForm.php(9): BaseClassLoader->{closure}('jojoe77777\\Form...')
#4 phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php(93): include('phar:///home/co...')
#5 phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php(83): BaseClassLoader->loadClass('jojoe77777\\Form...')
#6 phar:///home/container/plugins/Oneblock-PM4_dev-78 (2).phar/src/lenlenlL6/oneblock/command/OneblockCommand.php(50): BaseClassLoader->{closure}('jojoe77777\\Form...')
#7 phar:///home/container/plugins/Oneblock-PM4_dev-78 (2).phar/src/lenlenlL6/oneblock/command/OneblockCommand.php(42): lenlenlL6\oneblock\command\OneblockCommand->mainForm(Object(pocketmine\player\Player))
#8 phar:///home/container/PocketMine-MP.phar/src/command/SimpleCommandMap.php(205): lenlenlL6\oneblock\command\OneblockCommand->execute(Object(pocketmine\player\Player), 'oneblock', Array)
#9 phar:///home/container/PocketMine-MP.phar/src/Server.php(1429): pocketmine\command\SimpleCommandMap->dispatch(Object(pocketmine\player\Player), 'oneblock')
#10 phar:///home/container/PocketMine-MP.phar/src/player/Player.php(1509): pocketmine\Server->dispatchCommand(Object(pocketmine\player\Player), 'oneblock')
#11 phar:///home/container/PocketMine-MP.phar/src/network/mcpe/handler/InGamePacketHandler.php(823): pocketmine\player\Player->chat('/oneblock')
#12 phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket.php(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(Object(pocketmine\network\mcpe\protocol\CommandRequestPacket))
#13 phar:///home/container/PocketMine-MP.phar/src/network/mcpe/NetworkSession.php(433): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(Object(pocketmine\network\mcpe\handler\InGamePacketHandler))
#14 phar:///home/container/PocketMine-MP.phar/src/network/mcpe/NetworkSession.php(377): pocketmine\network\mcpe\NetworkSession->handleDataPacket(Object(pocketmine\network\mcpe\protocol\CommandRequestPacket), 'M\t/oneblock\x00\xCFAF...')
#15 phar:///home/container/PocketMine-MP.phar/src/network/mcpe/raklib/RakLibInterface.php(198): pocketmine\network\mcpe\NetworkSession->handleEncoded('\x93\xF7\xE5\xD4\xCF\xCFKM\xCA\xC9O\xCEf8\xEF...')
#16 phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver.php(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(0, '\xFE\x88\xDC\xCC\xDE\xEF%N\x8A\x9BR\xC1k\xD6\xA0...')
#17 phar:///home/container/PocketMine-MP.phar/src/network/mcpe/raklib/RakLibInterface.php(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(Object(pocketmine\network\mcpe\raklib\RakLibInterface))
#18 phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/snooze/src/SleeperHandler.php(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#19 phar:///home/container/PocketMine-MP.phar/src/TimeTrackingSleeperHandler.php(58): pocketmine\snooze\SleeperHandler->processNotifications()
#20 phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/snooze/src/SleeperHandler.php(82): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#21 phar:///home/container/PocketMine-MP.phar/src/Server.php(1688): pocketmine\snooze\SleeperHandler->sleepUntil(1684946434.245)
#22 phar:///home/container/PocketMine-MP.phar/src/Server.php(1068): pocketmine\Server->tickProcessor()
#23 phar:///home/container/PocketMine-MP.phar/src/PocketMine.php(336): pocketmine\Server->__construct(Object(BaseClassLoader), Object(pocketmine\utils\MainLogger), '/home/container...', '/home/container...')
#24 phar:///home/container/PocketMine-MP.phar/src/PocketMine.php(359): pocketmine\server()
#25 /home/container/PocketMine-MP.phar(11): require('phar:///home/co...')
#26 {main} in phar:///home/container/plugins/FormAPI_dev-2.phar/src/jojoe77777/FormAPI/Form.php on line 10
[16:40:34.239] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[16:40:34.247] [Server thread/EMERGENCY]: Please upload the "/home/container/crashdumps/Wed_May_24-23.40.34-+07_2023.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

**Comment by lenlenlL6** [comment]
> Fatal error: During inheritance of JsonSerializable: Uncaught ErrorException: Return type of jojoe77777\FormAPI\Form::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/container/plugins/FormAPI_dev-2.phar/src/jojoe77777/FormAPI/Form.php:53 Stack trace: #0 phar:///home/container/plugins/FormAPI_dev-2.phar/src/jojoe77777/FormAPI/Form.php(10): pocketmine\errorhandler\ErrorToExceptionHandler::handle(8192, 'Return type of ...', 'phar:///home/co...', 53) #1 phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php(93): include('phar:///home/co...') #2 phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php(83): BaseClassLoader->loadClass('jojoe77777\Form...') #3 phar:///home/container/plugins/FormAPI_dev-2.phar/src/jojoe77777/FormAPI/SimpleForm.php(9): BaseClassLoader->{closure}('jojoe77777\Form...') #4 phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php(93): include('phar:///home/co...') #5 phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php(83): BaseClassLoader->loadClass('jojoe77777\Form...') #6 phar:///home/container/plugins/Oneblock-PM4_dev-78 (2).phar/src/lenlenlL6/oneblock/command/OneblockCommand.php(50): BaseClassLoader->{closure}('jojoe77777\Form...') #7 phar:///home/container/plugins/Oneblock-PM4_dev-78 (2).phar/src/lenlenlL6/oneblock/command/OneblockCommand.php(42): lenlenlL6\oneblock\command\OneblockCommand->mainForm(Object(pocketmine\player\Player)) #8 phar:///home/container/PocketMine-MP.phar/src/command/SimpleCommandMap.php(205): lenlenlL6\oneblock\command\OneblockCommand->execute(Object(pocketmine\player\Player), 'oneblock', Array) #9 phar:///home/container/PocketMine-MP.phar/src/Server.php(1429): pocketmine\command\SimpleCommandMap->dispatch(Object(pocketmine\player\Player), 'oneblock') #10 phar:///home/container/PocketMine-MP.phar/src/player/Player.php(1509): pocketmine\Server->dispatchCommand(Object(pocketmine\player\Player), 'oneblock') #11 phar:///home/container/PocketMine-MP.phar/src/network/mcpe/handler/InGamePacketHandler.php(823): pocketmine\player\Player->chat('/oneblock') #12 phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket.php(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(Object(pocketmine\network\mcpe\protocol\CommandRequestPacket)) #13 phar:///home/container/PocketMine-MP.phar/src/network/mcpe/NetworkSession.php(433): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(Object(pocketmine\network\mcpe\handler\InGamePacketHandler)) #14 phar:///home/container/PocketMine-MP.phar/src/network/mcpe/NetworkSession.php(377): pocketmine\network\mcpe\NetworkSession->handleDataPacket(Object(pocketmine\network\mcpe\protocol\CommandRequestPacket), 'M\t/oneblock\x00\xCFAF...') #15 phar:///home/container/PocketMine-MP.phar/src/network/mcpe/raklib/RakLibInterface.php(198): pocketmine\network\mcpe\NetworkSession->handleEncoded('\x93\xF7\xE5\xD4\xCF\xCFKM\xCA\xC9O\xCEf8\xEF...') #16 phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver.php(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(0, '\xFE\x88\xDC\xCC\xDE\xEF%N\x8A\x9BR\xC1k\xD6\xA0...') #17 phar:///home/container/PocketMine-MP.phar/src/network/mcpe/raklib/RakLibInterface.php(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(Object(pocketmine\network\mcpe\raklib\RakLibInterface)) #18 phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/snooze/src/SleeperHandler.php(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib{closure}() #19 phar:///home/container/PocketMine-MP.phar/src/TimeTrackingSleeperHandler.php(58): pocketmine\snooze\SleeperHandler->processNotifications() #20 phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/snooze/src/SleeperHandler.php(82): pocketmine\TimeTrackingSleeperHandler->processNotifications() #21 phar:///home/container/PocketMine-MP.phar/src/Server.php(1688): pocketmine\snooze\SleeperHandler->sleepUntil(1684946434.245) #22 phar:///home/container/PocketMine-MP.phar/src/Server.php(1068): pocketmine\Server->tickProcessor() #23 phar:///home/container/PocketMine-MP.phar/src/PocketMine.php(336): pocketmine\Server->__construct(Object(BaseClassLoader), Object(pocketmine\utils\MainLogger), '/home/container...', '/home/container...') #24 phar:///home/container/PocketMine-MP.phar/src/PocketMine.php(359): pocketmine\server() #25 /home/container/PocketMine-MP.phar(11): require('phar:///home/co...') #26 {main} in phar:///home/container/plugins/FormAPI_dev-2.phar/src/jojoe77777/FormAPI/Form.php on line 10 [16:40:34.239] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump [16:40:34.247] [Server thread/EMERGENCY]: Please upload the "/home/container/crashdumps/Wed_May_24-23.40.34-+07_2023.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

What version of FormAPI are you using?
