### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by GamerMJay** [BeeAZZ/Oneblock-PM4#26]
[19:34:12.492] [Server thread/EMERGENCY]: Crash occurred while handling a packet from session: GamerMJayy
[19:34:12.494] [Server thread/CRITICAL]: pocketmine\data\bedrock\block\BlockStateSerializeException: "No serializer registered for pocketmine\block\UnknownBlock with type ID 40" (EXCEPTION) in "pmsrc/src/data/bedrock/block/convert/BlockObjectToStateSerializer" at line 248
--- Stack trace ---
  #0 pmsrc/src/data/bedrock/block/convert/BlockObjectToStateSerializer(206): pocketmine\data\bedrock\block\convert\BlockObjectToStateSerializer->serializeBlock(object pocketmine\block\UnknownBlock#85173)
  #1 pmsrc/src/world/format/io/leveldb/LevelDB(228): pocketmine\data\bedrock\block\convert\BlockObjectToStateSerializer->serialize(int 10282)
  #2 pmsrc/src/world/format/io/leveldb/LevelDB(761): pocketmine\world\format\io\leveldb\LevelDB->serializeBlockPalette(object pocketmine\utils\BinaryStream#84203, object pocketmine\world\format\PalettedBlockArray#89186)
  #3 pmsrc/src/world/World(2868): pocketmine\world\format\io\leveldb\LevelDB->saveChunk(int 16, int 16, object pocketmine\world\format\io\ChunkData#88032, int -1)
  #4 pmsrc/src/world/World(626): pocketmine\world\World->unloadChunk(int 16, int 16, false)
  #5 pmsrc/src/world/WorldManager(163): pocketmine\world\World->onUnload()
  #6 plugins/MultiWorld_dev-281.phar/src/czechpmdevs/multiworld/util/WorldUtils(63): pocketmine\world\WorldManager->unloadWorld(object pocketmine\world\World#59298, true)
  #7 plugins/MultiWorld_dev-281.phar/src/czechpmdevs/multiworld/command/subcommand/DeleteSubCommand(63): czechpmdevs\multiworld\util\WorldUtils::removeWorld(string[20] oneblock@@GamerMJayy)
  #8 plugins/MultiWorld_dev-281.phar/src/czechpmdevs/multiworld/libs/CortexPE/Commando/BaseCommand(144): czechpmdevs\multiworld\command\subcommand\DeleteSubCommand->onRun(object pocketmine\console\ConsoleCommandSender#119782, string[2] mw, array[1])
  #9 pmsrc/src/command/SimpleCommandMap(212): czechpmdevs\multiworld\libs\CortexPE\Commando\BaseCommand->execute(object pocketmine\console\ConsoleCommandSender#119782, string[2] mw, array[1])
  #10 pmsrc/src/Server(1415): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\console\ConsoleCommandSender#119782, string[30] mw delete oneblock@@GamerMJayy)
  #11 plugins/Oneblock-pm5/src/lenlenlL6/oneblock/command/OneblockCommand(133): pocketmine\Server->dispatchCommand(object pocketmine\console\ConsoleCommandSender#119782, string[30] mw delete oneblock@@GamerMJayy)
  #12 plugins/FormAPI-master/src/jojoe77777/FormAPI/Form(46): lenlenlL6\oneblock\command\OneblockCommand->lenlenlL6\oneblock\command\{closure}(object pocketmine\player\Player#140774, int 3)
  #13 pmsrc/src/player/Player(2117): jojoe77777\FormAPI\Form->handleResponse(object pocketmine\player\Player#140774, int 3)
  #14 pmsrc/src/network/mcpe/handler/InGamePacketHandler(975): pocketmine\player\Player->onFormSubmit(int 1, int 3)
  #15 pmsrc/vendor/pocketmine/bedrock-protocol/src/ModalFormResponsePacket(63): pocketmine\network\mcpe\handler\InGamePacketHandler->handleModalFormResponse(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#119734)
  #16 pmsrc/src/network/mcpe/NetworkSession(438): pocketmine\network\mcpe\protocol\ModalFormResponsePacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#79539)
  #17 pmsrc/src/network/mcpe/NetworkSession(382): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#119734, string[7] e...3..)
  #18 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[10] cOedd2.b..)
  #19 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[19] .L^`dNN.J..R....e..)
  #20 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#169421)
  #21 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #22 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #23 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #24 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1690306452.4882)
  #25 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #26 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[22] /home/Server/OneBlock/, string[30] /home/Server/OneBlock/plugins/)
  #27 pmsrc/src/PocketMine(357): pocketmine\server()
  #28 pmsrc(11): require(string[66] phar:///home/Server/OneBlock/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---
[19:34:12.494] [Server thread/EMERGENCY]: Ein nicht-behebbarer Fehler ist aufgetreten und der Server stürzte ab. Erstelle einen Crash-Dump...
[19:34:12.504] [Server thread/EMERGENCY]: Bitte lade die "/home/Server/OneBlock/crashdumps/Tue_Jul_25-19.34.12-CEST_2023.log" Datei in das Crash-Archiv hoch und reiche den Link auf der Bug-Reporting Seite ein. Gib so viele Informationen wie möglich.
[19:34:12.504] [Server thread/EMERGENCY]: Forcing server shutdown

**Comment by lenlenlL6** [comment]
> [19:34:12.492] [Server thread/EMERGENCY]: Crash occurred while handling a packet from session: GamerMJayy [19:34:12.494] [Server thread/CRITICAL]: pocketmine\data\bedrock\block\BlockStateSerializeException: "No serializer registered for pocketmine\block\UnknownBlock with type ID 40" (EXCEPTION) in "pmsrc/src/data/bedrock/block/convert/BlockObjectToStateSerializer" at line 248 --- Stack trace --- #0 pmsrc/src/data/bedrock/block/convert/BlockObjectToStateSerializer(206): pocketmine\data\bedrock\block\convert\BlockObjectToStateSerializer->serializeBlock(object pocketmine\block\UnknownBlock#85173) #1 pmsrc/src/world/format/io/leveldb/LevelDB(228): pocketmine\data\bedrock\block\convert\BlockObjectToStateSerializer->serialize(int 10282) #2 pmsrc/src/world/format/io/leveldb/LevelDB(761): pocketmine\world\format\io\leveldb\LevelDB->serializeBlockPalette(object pocketmine\utils\BinaryStream#84203, object pocketmine\world\format\PalettedBlockArray#89186) #3 pmsrc/src/world/World(2868): pocketmine\world\format\io\leveldb\LevelDB->saveChunk(int 16, int 16, object pocketmine\world\format\io\ChunkData#88032, int -1) #4 pmsrc/src/world/World(626): pocketmine\world\World->unloadChunk(int 16, int 16, false) #5 pmsrc/src/world/WorldManager(163): pocketmine\world\World->onUnload() #6 plugins/MultiWorld_dev-281.phar/src/czechpmdevs/multiworld/util/WorldUtils(63): pocketmine\world\WorldManager->unloadWorld(object pocketmine\world\World#59298, true) #7 plugins/MultiWorld_dev-281.phar/src/czechpmdevs/multiworld/command/subcommand/DeleteSubCommand(63): czechpmdevs\multiworld\util\WorldUtils::removeWorld(string[20] oneblock@@GamerMJayy) #8 plugins/MultiWorld_dev-281.phar/src/czechpmdevs/multiworld/libs/CortexPE/Commando/BaseCommand(144): czechpmdevs\multiworld\command\subcommand\DeleteSubCommand->onRun(object pocketmine\console\ConsoleCommandSender#119782, string[2] mw, array[1]) #9 pmsrc/src/command/SimpleCommandMap(212): czechpmdevs\multiworld\libs\CortexPE\Commando\BaseCommand->execute(object pocketmine\console\ConsoleCommandSender#119782, string[2] mw, array[1]) #10 pmsrc/src/Server(1415): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\console\ConsoleCommandSender#119782, string[30] mw delete oneblock@@GamerMJayy) #11 plugins/Oneblock-pm5/src/lenlenlL6/oneblock/command/OneblockCommand(133): pocketmine\Server->dispatchCommand(object pocketmine\console\ConsoleCommandSender#119782, string[30] mw delete oneblock@@GamerMJayy) #12 plugins/FormAPI-master/src/jojoe77777/FormAPI/Form(46): lenlenlL6\oneblock\command\OneblockCommand->lenlenlL6\oneblock\command{closure}(object pocketmine\player\Player#140774, int 3) #13 pmsrc/src/player/Player(2117): jojoe77777\FormAPI\Form->handleResponse(object pocketmine\player\Player#140774, int 3) #14 pmsrc/src/network/mcpe/handler/InGamePacketHandler(975): pocketmine\player\Player->onFormSubmit(int 1, int 3) #15 pmsrc/vendor/pocketmine/bedrock-protocol/src/ModalFormResponsePacket(63): pocketmine\network\mcpe\handler\InGamePacketHandler->handleModalFormResponse(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#119734) #16 pmsrc/src/network/mcpe/NetworkSession(438): pocketmine\network\mcpe\protocol\ModalFormResponsePacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#79539) #17 pmsrc/src/network/mcpe/NetworkSession(382): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#119734, string[7] e...3..) #18 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[10] cOedd2.b..) #19 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[19] .L^`dNN.J..R....e..) #20 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#169421) #21 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib{closure}() #22 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications() #23 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications() #24 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1690306452.4882) #25 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor() #26 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[22] /home/Server/OneBlock/, string[30] /home/Server/OneBlock/plugins/) #27 pmsrc/src/PocketMine(357): pocketmine\server() #28 pmsrc(11): require(string[66] phar:///home/Server/OneBlock/PocketMine-MP.phar/src/PocketMine.php) --- End of exception information --- [19:34:12.494] [Server thread/EMERGENCY]: Ein nicht-behebbarer Fehler ist aufgetreten und der Server stürzte ab. Erstelle einen Crash-Dump... [19:34:12.504] [Server thread/EMERGENCY]: Bitte lade die "/home/Server/OneBlock/crashdumps/Tue_Jul_25-19.34.12-CEST_2023.log" Datei in das Crash-Archiv hoch und reiche den Link auf der Bug-Reporting Seite ein. Gib so viele Informationen wie möglich. [19:34:12.504] [Server thread/EMERGENCY]: Forcing server shutdown

When does this error appear?

**Comment by lenlenlL6** [comment]
You have edited the "id" of a block that does not exist.
