### ISSUE TITLE
The server crashed when I enter the command /oneblock

### ISSUE THREAD

**Issue by JYan0614** [BeeAZZ/Oneblock-PM4#27]
2023-07-26 [14:03:24.879] [Server thread/EMERGENCY]: Crash occurred while handling a packet from session: always12y
2023-07-26 [14:03:24.880] [Server thread/CRITICAL]: Error: "Class "jojoe77777\FormAPI\SimpleForm" not found" (EXCEPTION) in "plugins/Oneblock.phar/src/lenlenlL6/oneblock/command/OneblockCommand" at line 59
--- Stack trace ---
  #0 plugins/Oneblock.phar/src/lenlenlL6/oneblock/command/OneblockCommand(45): lenlenlL6\oneblock\command\OneblockCommand->mainForm(object pocketmine\player\Player#167481)
  #1 pmsrc/src/command/SimpleCommandMap(212): lenlenlL6\oneblock\command\OneblockCommand->execute(object pocketmine\player\Player#167481, string[8] oneblock, array[0])
  #2 pmsrc/src/Server(1415): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#167481, string[8] oneblock)
  #3 pmsrc/src/player/Player(1503): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#167481, string[8] oneblock)
  #4 pmsrc/src/network/mcpe/handler/InGamePacketHandler(823): pocketmine\player\Player->chat(string[9] /oneblock)
  #5 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#174160)
  #6 pmsrc/src/network/mcpe/NetworkSession(438): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#94299)
  #7 pmsrc/src/network/mcpe/NetworkSession(382): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#174160, string[31] M./oneblock..@O.r.;...........F)
  #8 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[81] ......KM..O.f.....h.5...Q.././a`p...x.....>..3_Mv..mw2..rf...xCC......n.....{...)
  #9 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[90] .v......)%......U7..._.bX6AM..7.]...=..z....1X}......~1m...S.j....:..R./q.......)
  #10 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#168033)
  #11 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #12 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #14 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1690373004.8873)
  #15 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #16 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[8] /server/, string[16] /server/plugins/)
  #17 pmsrc/src/PocketMine(357): pocketmine\server()
  #18 pmsrc(11): require(string[45] phar:///server/server.phar/src/PocketMine.php)
--- End of exception information ---
2023-07-26 [14:03:24.881] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
2023-07-26 [14:03:24.887] [Server thread/EMERGENCY]: Please upload the "/server/crashdumps/Wed_Jul_26-14.03.24-CEST_2023.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
2023-07-26 [14:03:25.345] [Server thread/EMERGENCY]: The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/9023357 or use the ID #9023357.
2023-07-26 [14:03:25.346] [Server thread/EMERGENCY]: F

**Comment by lenlenlL6** [comment]
> 2023-07-26 [14:03:24.879] [Server thread/EMERGENCY]: Crash occurred while handling a packet from session: always12y 2023-07-26 [14:03:24.880] [Server thread/CRITICAL]: Error: "Class "jojoe77777\FormAPI\SimpleForm" not found" (EXCEPTION) in "plugins/Oneblock.phar/src/lenlenlL6/oneblock/command/OneblockCommand" at line 59 --- Stack trace --- #0 plugins/Oneblock.phar/src/lenlenlL6/oneblock/command/OneblockCommand(45): lenlenlL6\oneblock\command\OneblockCommand->mainForm(object pocketmine\player\Player#167481) #1 pmsrc/src/command/SimpleCommandMap(212): lenlenlL6\oneblock\command\OneblockCommand->execute(object pocketmine\player\Player#167481, string[8] oneblock, array[0]) #2 pmsrc/src/Server(1415): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#167481, string[8] oneblock) #3 pmsrc/src/player/Player(1503): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#167481, string[8] oneblock) #4 pmsrc/src/network/mcpe/handler/InGamePacketHandler(823): pocketmine\player\Player->chat(string[9] /oneblock) #5 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#174160) #6 pmsrc/src/network/mcpe/NetworkSession(438): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#94299) #7 pmsrc/src/network/mcpe/NetworkSession(382): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#174160, string[31] M./[oneblock..@O.r](mailto:oneblock..@O.r).;...........F) #8 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[81] ......KM..O.f.....h.5...Q.././a`p...x.....>..3_Mv..mw2..rf...xCC......n.....{...) #9 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[90] .v......)%......U7..._.bX6AM..7.]...=..z....1X}......~1m...S.j....:..R./q.......) #10 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#168033) #11 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib{closure}() #12 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications() #13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications() #14 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1690373004.8873) #15 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor() #16 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[8] /server/, string[16] /server/plugins/) #17 pmsrc/src/PocketMine(357): pocketmine\server() #18 pmsrc(11): require(string[45] phar:///server/server.phar/src/PocketMine.php) --- End of exception information --- 2023-07-26 [14:03:24.881] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump 2023-07-26 [14:03:24.887] [Server thread/EMERGENCY]: Please upload the "/server/crashdumps/Wed_Jul_26-14.03.24-CEST_2023.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can. 2023-07-26 [14:03:25.345] [Server thread/EMERGENCY]: The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/9023357 or use the ID #9023357. 2023-07-26 [14:03:25.346] [Server thread/EMERGENCY]: F

You have not installed FormAPI
