### ISSUE TITLE
please

### ISSUE THREAD

**Issue by DimonYoing** [BeeAZZ/Oneblock-PM4#7]
Create the ID item plugin, if you enter the /ID command, then the block ID is written to the chat.
In plugin.yml add command description

**Comment by JeroGamingYT** [comment]
let me ask a small problem: how does the issues you give help oneblock ?

**Comment by JeroGamingYT** [comment]
I have a small question: how does it help oneblock ?

**Comment by lenlenlL6** [comment]
Dear @DimonYoing ,

> I regret to inform you that your issues has been rejected.
