### ISSUE TITLE
Idea: Add a config file

### ISSUE THREAD

**Issue by ricky074game** [BeeAZZ/Oneblock-PM4#9]
I wish there is a config file, in which we could change what each tier would give. 
It could contain how many blocks to contain until to advance to the next tier. 
It could be in the format of:
Tiers:
   1:
        Wood (15)  
        Blockxyz (99)
   2:
      etc.

**Comment by 0xliam627** [comment]
very good idea! I will do it if you see this answer please reply me!

**Comment by lenlenlL6** [comment]
> I wish there is a config file, in which we could change what each tier would give. It could contain how many blocks to contain until to advance to the next tier. It could be in the format of: Tiers: 1: Wood (15) Blockxyz (99) 2: etc.
Thank you for your feedback, I have updated the new version please check it: https://github.com/lenlenlL6/Oneblock-PM4/releases/tag/VERSION-0.0.3

**Comment by ricky074game** [comment]
Yes, I would like it to be inside this plugin.
You can always contact me if you need to tell me what to be inside the config file

**Comment by ricky074game** [comment]
Yes, I would like this to be in the plugin. Please contact me inrder to tell me what ti be in the config file
